---

- hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - role: terraform

- hosts: www
  become: yes
  gather_facts: no

  roles:
    - role: www

  remote_user: csullivan
  vars:
    ansible_ssh_private_key_file: id_azure
